let ActionKey;
export default ActionKey = [
    {id: 1, key: 'Contestant is chosen for a date', points: 5, category: 'MultiplePerEpisode'},
    {id: 2, key: 'Contestant advances/receives rose', points: 10, category: 'MultiplePerEpisode'},
    {id: 3, key: 'Contestant receives rose during a date (bonus)', points: 5, category: 'MultiplePerEpisode'},
    {id: 4, key: 'Contestant gets a word bleeped out', points: 7, category: 'OncePerEpisode'},
    {id: 5, key: 'Contestant is on camera shirtless (not during swimming/beach date)', points: 7, category: 'OncePerEpisode'},
    {id: 6, key: 'Contestant is on camera shirtless and doesn_t have a six-pack (bonus for bravery)', points: 1, category: 'OncePerEpisode'},
    {id: 7, key: 'Does not advance', points: -12, category: 'OncePerEpisode'},
    {id: 8, key: 'Dumped outside of a rose ceremony (bonus)', points: -5, category: 'OncePerEpisode'},
    {id: 9, key: 'Kisses Bachelorette', points: 5, category: 'OncePerEpisode'},
    {id: 10, key: 'Full on hard core gross make out with the Bachelorette (bonus)', points: 3, category: 'OncePerEpisode'},
    {id: 11, key: 'Cries', points: 10, category: 'MultiplePerEpisode'},
    {id: 12, key: 'Reads the date card', points: 3, category: 'MultiplePerEpisode'},
    {id: 13, key: 'First to be seen hugging The Bachelorette during a group date', points: 4, category: 'MultiplePerEpisode'},
    {id: 14, key: 'Bachelorette gives contestant a wrap-around/jump & straddle hug', points: 5, category: 'MultiplePerEpisode'},
    {id: 15, key: 'Contest is shown on the phone/video chatting with friends/family during the season', points: 5, category: 'MultiplePerEpisode'},
    {id: 16, key: 'Dances with the Bachelorette', points: 10, category: 'MultiplePerEpisode'},
    {id: 17, key: 'Contestant is seen popping a bottle of champagne', points: 10, category: 'MultiplePerEpisode'},
    {id: 18, key: 'Selected for a 2 on 1 date (bonus)', points: 7, category: 'MultiplePerEpisode'},
    {id: 19, key: 'Steals the Bachelorette from another contestant when they already have a rose', points: 5, category: 'MultiplePerEpisode'},
    {id: 20, key: 'Takes a shot/shotguns (clearly chugging alc)', points: 8, category: 'MultiplePerEpisode'},
    {id: 21, key: 'Vomits', points: 12, category: 'MultiplePerEpisode'},
    {id: 22, key: 'Non-sanctioned violence (push or punch) against another contestant', points: 20, category: 'MultiplePerEpisode'},
    {id: 23, key: 'Requires an ambulance being called', points: 25, category: 'MultiplePerEpisode'},
    {id: 24, key: 'Runs away in the middle of a rose ceremony', points: -10, category: 'MultiplePerEpisode'},
    {id: 25, key: 'Contestant sings', points: 5, category: 'OncePerEpisode'},
    {id: 26, key: 'Contestant is seen in hot tub', points: 5, category: 'OncePerEpisode'},
    {id: 27, key: 'Kisses Bachelorette in water (bonus)', points: 5, category: 'OncePerEpisode'},
    {id: 28, key: 'Kiss outside in the rain or snow (bonus)', points: 10, category: 'OncePerEpisode'},
    {id: 29, key: 'Contestant wins a group competition (can be individually or as part of group)', points: 7, category: 'OncePerEpisode'},
    {id: 30, key: 'Contestant wins solo time after a group date (2 on 1 or more)', points: 7, category: 'OncePerEpisode'},
    {id: 31, key: 'Jumps into water holding hands with the Bachelorette', points: 7, category: 'OncePerEpisode'},
    {id: 32, key: 'Has 1 on 1 conversation with Chris Harrison', points: 10, category: 'OncePerEpisode'},
    {id: 33, key: 'Date involves animals', points: 10, category: 'OncePerEpisode'},
    {id: 34, key: 'Date includes fireworks', points: 10, category: 'OncePerEpisode'},
    {id: 35, key: 'Contestant is seen eating (food must be seen entering mouth)', points: 10, category: 'OncePerEpisode'},
    {id: 36, key: 'Contestant is covered by a black box', points: 10, category: 'OncePerEpisode'},
    {id: 37, key: 'Contestant sneaks into Bachelorette’s residence outside of sanctioned date time', points: 12, category: 'OncePerEpisode'},
    {id: 38, key: 'Contestant plays a musical instrument', points: 12, category: 'OncePerEpisode'},
    {id: 39, key: 'Has to quarantine for suspected covid (not tested yet/results pending)', points: 12, category: 'OncePerEpisode'},
    {id: 40, key: 'Naked in front of The Bachelorette', points: 15, category: 'OncePerEpisode'},
    {id: 41, key: 'Talks about ex', points: 5, category: 'OncePerEpisode'},
    {id: 42, key: 'Talks about being cheated on', points: 7, category: 'OncePerEpisode'},
    {id: 43, key: 'Brings up an ex who was a past Bach contestant', points: 15, category: 'OncePerEpisode'},
    {id: 44, key: 'Tests positive for corona (+7 if already quarantined)', points: 19, category: 'OncePerEpisode'},
    {id: 45, key: 'Contestant_s ex shows up', points: 25, category: 'OncePerEpisode'},
    {id: 46, key: 'Bachelorette says contestant “won’t/will not/hasn’t open(ed) up”', points: -5, category: 'OncePerEpisode'},
    {id: 47, key: 'Contestant makes Bachelorette cry (either through something they said to her or did - so if Paul tells the Bachelorette that Chad did XYZ shitty thing and the Bachelorette cries they both lose points)', points: -10, category: 'OncePerEpisode'},
    {id: 48, key: 'Contestant leaves of their own accord/not sent home by the Bachelorette (unless for emergency reasons)', points: -20, category: 'OncePerEpisode'},
    {id: 49, key: 'Contestant reveals a diagnosed history of mental illness (i.e. a condition they got therapy/medicaiton for, not just that they were anxious growing up).', points: 5, category: 'OncePerContestant'},
    {id: 50, key: 'Contestant reveals a diagnosed history of mental illness other than depression/anxiety (bonus)', points: 5, category: 'OncePerContestant'},
    {id: 51, key: 'Contestant reveals their very traumatic* backstory to Bachelorette', points: 10, category: 'OncePerContestant'},
    {id: 52, key: 'Contestant tells the Bachelorette he_s "falling in love" with her', points: 15, category: 'OncePerContestant'},
    {id: 53, key: 'Contestant tells the Bachelorette he_s in love with her/loves her (in a serious way)', points: 20, category: 'OncePerContestant'},
    {id: 54, key: 'Contestant reveals he_s bi/trans/member of LGBTQ community', points: 25, category: 'OncePerContestant'},
    {id: 55, key: 'Bachelorette says she_s falling in love with a contestant (not to their face - no points if already said to the contestants face)', points: 10, category: 'OncePerContestant'},
    {id: 56, key: 'Bachelorette says she_s falling in love with a contestant (to their face - if already got points for the Bachelorette telling the camera crew/Chris that she_s falling in love with them +5, if said to contestant first +15)', points: 15, category: 'OncePerContestant'},
    {id: 57, key: 'Bachelorette says she loves a contestant (not to their face - no points if already said to the contestants face)', points: 15, category: 'OncePerContestant'},
    {id: 58, key: 'Bachelorette says she loves a contestant (to their face - if already got points for the Bachelorette telling the camera crew/Chris that she_s in love with the contestant +5, if said to contestant first +20', points: 20, category: 'OncePerContestant'},
    {id: 59, key: 'Contestant wins season (Leaves with Clare or Tayshia_s final pick)', points: 25, category: 'OncePerEpisode'},
    {id: 60, key: 'Contestant wins season but they split up before After the Final Rose (in non-Jed-like circumstances)', points: -15, category: 'OncePerEpisode'},
    {id: 61, key: 'Contestant wins season but the Bachelor pulls an Arie/Peter and switches to picking someone else', points: -10, category: 'OncePerEpisode'},
    {id: 62, key: 'Contestant loses season but the Bachelor pulls an Arie/Peter and switches to picking them after proposing to someone else', points: 10, category: 'OncePerEpisode'},
    {id: 63, key: 'Contestant pulls a Jed and wins the season only to reveal they just wanted fame (or some other dick move) and they break up with the bachelor', points: -30, category: 'OncePerEpisode'},
    {id: 64, key: 'First 1-on-1 hot tub date with the Bachelorette', points: 5, category: 'Firsts'},
    {id: 65, key: 'First horseback riding date', points: 5, category: 'Firsts'},
    {id: 66, key: 'First helicopter or plane ride with the Bachelorette', points: 10, category: 'Firsts'},
    {id: 67, key: 'First boat ride with the Bachelorette', points: 10, category: 'Firsts'},
    {id: 68, key: 'First person to meet a member of the Bachelorette’s family (in person or virtually)', points: 18, category: 'Firsts'},
    {id: 69, key: 'First contestant to mention their divorce to the Bachelorette', points: 5, category: 'Firsts'},
    {id: 70, key: 'First contestant to mention their kids to the Bachelorette', points: 8, category: 'Firsts'},
    {id: 71, key: 'First contestant to mention their pet to the Bachelorette', points: 12, category: 'Firsts'},
    {id: 72, key: 'First kiss with the Bachelorette after limo intros end', points: 12, category: 'Firsts'},
    {id: 73, key: 'First person to mention Juan Pablo', points: -5, category: 'Firsts'},
    {id: 74, key: 'First person to mention Benoit', points: -5, category: 'Firsts'},
    {id: 75, key: 'First person to mention Colton', points: -5, category: 'Firsts'},
    {id: 76, key: 'First person to mention JPJ', points: -5, category: 'Firsts'},
    {id: 77, key: 'First bad pun (by definition all puns are bad) during the limo intro', points: 5, category: 'Firsts'},
    {id: 78, key: 'Contestant wears a mask during their limo intro (doesn_t count as prop/costume)', points: 3, category: 'OncePerEpisode'},
    {id: 79, key: 'Makes a corona joke (in a non-science-denial-way) in their limo intro', points: 5, category: 'OncePerEpisode'},
    {id: 80, key: 'Contestant speaks a foreign language during their limo intro', points: 5, category: 'OncePerEpisode'},
    {id: 81, key: 'Contestant brings a prop to their limo intro', points: 8, category: 'OncePerEpisode'},
    {id: 82, key: 'Contestant wears a costume during their limo intro', points: 10, category: 'OncePerEpisode'},
    {id: 83, key: 'Contestant kisses Bachelorette (on lips) during limo intro - consent is important people', points: -10, category: 'OncePerEpisode'},
    {id: 84, key: 'First solo time with the Bachelorette (after limos)', points: 7, category: 'Firsts'},
    {id: 85, key: 'First contestant to steal the Bachelorette away from another contestant', points: 7, category: 'Firsts'},
    {id: 86, key: 'Contestant receives first impression rose (bonus)', points: 10, category: 'OncePerEpisode'},
    {id: 87, key: 'Contestant refers to the Bachelorette as his “girlfriend”', points: 5, category: 'OncePerEpisode'},
    {id: 88, key: 'Contestant says “I was hoping it would be you/her/the Bachelorette” or “I was hoping for you/her/the Bachelorette”', points: 5, category: 'OncePerEpisode'},
    {id: 89, key: 'Mentions "corona" "covid " "pandemic" "mask" "social distancing" or staying "6 feet" away (in a non-science-denial-way)', points: 5, category: 'OncePerEpisode'},
    {id: 90, key: 'Contestant says someone is “Not here for the right reasons”', points: 10, category: 'OncePerEpisode'},
    {id: 91, key: 'Contestant says someone is “disngenuine/disingenuous ”', points: 10, category: 'OncePerEpisode'},
    {id: 92, key: 'Contestant says “I’m not here to make friends”', points: 10, category: 'OncePerEpisode'},
    {id: 93, key: 'Contestant says corona is a hoax/refuses to wear a mask/general corona denial', points: -10, category: 'OncePerEpisode'},
    {id: 94, key: 'Contestant says: “I’m not ready for marriage” / “I’m not ready to get married” / “I’m not ready to get engaged” / “I’m not ready to be engaged”', points: -12, category: 'OncePerEpisode'}]